run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - goimports
    - golint
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - gosec
    - gocritic
    - gofmt
    - gocyclo
    - goconst

linters-settings:
  goimports:
    local-prefixes: github.com/yourusername/perplexity-mcp-golang
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2