# See the dedicated "version" documentation section.
version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: readonly
  issues-exit-code: 2
  tests: false
  allow-parallel-runners: true
  allow-serial-runners: true
  go: '1.25.1'
  concurrency: 2

linters:
  default: standard
